language: node_js
node_js:
  - "10"
os:
  - linux
  - osx


before_script:
  - npm install -g create-react-app
script:
  - npm install
  - npm run-script electron-builder
after_success:
  # so, pass the test...
  - echo '(￣▽￣)~*' cheers!


deploy:
  provider: releases
  file: "dist"
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file_glob: true
  on:
    branch: master
