language: node_js
node_js:
  - "14"
os:
  - linux
  - osx
  - windows


before_script:
  - npm install -g create-react-app
script:
  - npm install
  - npm run-script electron-builder
after_success:
  # so, pass the test...
  - echo '(￣▽￣)~*' cheers!



before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "jskyzero"
  - git config --local user.email "jskyzero@outlook.com"
  # - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - export TRAVIS_TAG="0.1.1"
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  file: "dist"
  api_key: $GITHUB_TOKEN
  file_glob: true
  on:
    branch: master
